### ISSUE TITLE
Failed to detect set build pack

### ISSUE THREAD

**Issue by bitscraps** [dive-networks/heroku-buildpack-git-sha#1]
Trying to use this with multiple build packs.  But cannot compile a slug as i get the following error. 

remote: Building source:

remote: 
remote: -----> Deleting 2 files matching .slugignore patterns.

remote: -----> Fetching set buildpack https://github.com/dive-networks/heroku-buildpack-git-sha.git... done

remote: 
remote:  !     Push rejected, failed to detect set buildpack https://github.com/dive-networks/heroku-buildpack-git-sha.git

remote: More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure

remote: 
remote: Verifying deploy....

remote: 
remote: !   Push rejected 

 I am not using with the multi build pack build pack just using heroku's builtin ability to utilise multiple build packs, is the multi build pack build pack a requirement?

Adding the build pack using:

`heroku buildpacks:add --index 1 https://github.com/dive-networks/heroku-buildpack-git-sha.git`

**Comment by sir-pinecone** [comment]
@bitscraps I'll take a look at this tonight. Can you tell me which Heroku stack you're using and can you paste the output of `heroku buildpacks`?

**Comment by bitscraps** [comment]
Thanks a lot for taking a look.

We are using Cedar-14

This is the output of heroku build pack:

=== sofar-dev Buildpack URLs
1. https://github.com/dive-networks/heroku-buildpack-git-sha.git
2. heroku/ruby

**Comment by bitscraps** [comment]
I don't have much familiarity with build packs but i would assume that message would be shown if it fails the detect script in bin, which in your app always returns successfully?

**Comment by sir-pinecone** [comment]
Hmm, I replicated your setup using my app and it fails as well. I'm not sure why and I unfortunately don't have much time on hand to investigate further. The detect script in bin should cause it to pass because of the `exit 0`. This [blog post](https://devcenter.heroku.com/changelog-items/653) makes it sound like it should work as well.

So for the time being, https://github.com/heroku/heroku-buildpack-multi is a requirement to get this to work. Let me know how it goes.

**Comment by bitscraps** [comment]
Thanks for taking the time too look into this.  Ive taken a look and forked the repo.  After looking into it i have got it to work with herokus support for multiple build packs by returning 0 in the compile script swell as i believe this is where it was failing.  So it no longer requires the multi build pack build pack. I have submitted to you a pull request.

**Comment by sir-pinecone** [comment]
No problem dude. Thanks for the PR, that's awesome!
